import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
// import registerServiceWorker from './registerServiceWorker';
// import register from './sw.js';
import LocalServiceWorkerRegister from './sw.register.js';
ReactDOM.render(<App />, document.getElementById('root'));
// registerServiceWorker();
// register();
LocalServiceWorkerRegister();